ALL_DIALECTS = [
    "postgres",
    "ansi",
    "bigquery",
    "bq",
    "clickhouse",
    "generic",
    "hive",
    "ms",
    "mssql",
    "mysql",
    "redshift",
    "snowflake",
    "sqlite",
]

conn_to_dialect_map = {
    "azure_sqldb": "mssql",
    "snowflake": "snowflake",
    "athena": "postgres",
    "bigquery": "bigquery",
    "postgres": "postgres",
    "redshift": "redshift",
    "amazonredshift": "redshift",
    "oracle": "oracle",
    "mssql": "mssql",
    "hadoophive": "hive",
    "vertica": "postgres",
    "memsql": "postgres",
    "genericodbc": "postgres",
    "presto": "postgres",
    "mysql": "postgres",
    "sqlserver": "postgres",
    "sqlite": "sqlite",
    "trino": "postgres",
    "databricks": "databricks",
}
