services:
  neo4j:
    image: neo4j:2025.09.0
    container_name: neo4j
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_server_config_strict__validation_enabled: "false"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms_security_auth__minimum__password__length: "3"

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  neo4j_import:
